### ISSUE TITLE
Executors should get the metrics.properties file before the metrics system is initialized

### ISSUE THREAD

**Issue by kimoonkim** [apache-spark-on-k8s/spark#162]
Not urgent to fix, but I wanted to keep a record.

I was submitting a Spark job specifying both `--conf spark.metrics.conf=metrics.properties` and `--files=metrics.properties`.
```
$ /usr/local/spark-on-k8s/bin/spark-submit  \
    --class org.apache.spark.examples.SparkPi  \
   ...
    --conf spark.metrics.conf=metrics.properties  \
    --files=metrics.properties  \
    /usr/local/spark-on-k8s/examples/jars/spark-examples_2.11-2.2.0-SNAPSHOT.jar 10000
```

The metrics.properties file resides on my Macbook. The content is something like:
```
$ cat metrics.properties
*.sink.graphite.class=org.apache.spark.metrics.sink.GraphiteSink
*.sink.graphite.host=graphite-exporter
*.sink.graphite.port=9109
*.sink.graphite.period=5
*.sink.graphite.unit=seconds
# Enable jvm source for instance master, worker, driver and executor
driver.source.jvm.class=org.apache.spark.metrics.source.JvmSource
executor.source.jvm.class=org.apache.spark.metrics.source.JvmSource
```

The intention is to affect the driver and executors so they send metrics to a prometheus graphite-exporter service. (See #88 for the background) This worked with the driver, but not with the executors. The file is successfully copied to the executor pods, but not before the metrics system is initialized. Here is the log:
```
$ kubectl logs -f spark-pi-1488323595540-exec-2 | grep metrics
2017-02-28 23:15:13 ERROR MetricsConfig:91 - Error loading configuration file metrics.properties
java.io.FileNotFoundException: metrics.properties (No such file or directory)
	at org.apache.spark.metrics.MetricsConfig.loadPropertiesFromFile(MetricsConfig.scala:132)
	at org.apache.spark.metrics.MetricsConfig.initialize(MetricsConfig.scala:55)
	at org.apache.spark.metrics.MetricsSystem.<init>(MetricsSystem.scala:95)
	at org.apache.spark.metrics.MetricsSystem$.createMetricsSystem(MetricsSystem.scala:233)
2017-02-28 23:15:14 INFO  Executor:54 - Fetching spark://10.40.0.12:7078/files/metrics.properties with timestamp 1488323649746
2017-02-28 23:15:14 INFO  Utils:54 - Fetching spark://10.40.0.12:7078/files/metrics.properties to /tmp/spark-8d906b40-1c8e-4f1f-930c-7c653b312d23/fetchFileTemp3469436879099132054.tmp
2017-02-28 23:15:14 INFO  Utils:54 - Copying /tmp/spark-8d906b40-1c8e-4f1f-930c-7c653b312d23/-17896059041488323649746_cache to /opt/spark/./metrics.properties
```

Above, you can see an error message from `MetricsConfig` complaining about the missing file. But then later you see the file is fetched from the driver, which is again too late.

I looked at the related [YARN code](https://github.com/apache-spark-on-k8s/spark/blob/k8s-support-alternate-incremental/resource-managers/yarn/src/main/scala/org/apache/spark/deploy/yarn/Client.scala) (See the `createConfArchive` method in the class). It turned out YARN handles this as a special case so that `metrics.properties` file is copied in place by the NodeManager daemon before the driver and executor JVMs start. (As an aside, this code also handles distribution of Hadoop config files mentioned in #130) 

So we may need to do something similar to be in par. I wonder if we considered having a rest endpoint in the executor pods as well.

But again, this is not urgent. There are a few known workarounds:
- One could prefix metrics config keys with `spark.metrics.conf` and put them in `--conf` options. (e.g.  `--conf spark.metrics.conf.*.sink.graphite.class=org.apache.spark.metrics.sink.GraphiteSink` for the first line in the `metrics.properties` file above).
- Or, one could put the `metrics.properties` file in a custom docker image.

**Comment by tnachen** [comment]
Probably can be just pushed to file staging server if we agree on that approach
