### ISSUE TITLE
Use tini to prevent JVM as pid1 errors

### ISSUE THREAD

**Issue by ash211** [apache-spark-on-k8s/spark#317]
https://github.com/krallin/tini

quick summary is running JVMs as pid1 in dockerfiles cause problems -- search for `Caused by: com.sun.tools.attach.AttachNotSupportedException: Unable to get pid of LinuxThreads manager thread at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:86)` to see examples

**Comment by ash211** [comment]
The full stacktrace of what we were seeing is available here: https://github.com/palantir/http-remoting/issues/403

Here's some more analysis I did internally on the stacktrace:

> ```
> Caused by: com.sun.tools.attach.AttachNotSupportedException: Unable to get pid of LinuxThreads manager thread
>     at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:86)
>     ... 64 more
> ```
> 
> The reason PID1 is important is that there's a bug in the JRE that doesn't correctly handle the JRE being pid1 (and having more child processes than expected).
> 
> The above stacktrace has [LinuxVirtualMachine.java/#86](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/sun/tools/attach/LinuxVirtualMachine.java/#86) in it from the call to native method `getLinuxThreadsManager` a few lines earlier.  [LinuxVirtualMachine.c#255](http://code.metager.de/source/xref/openjdk/jdk8/jdk/src/solaris/native/sun/tools/attach/LinuxVirtualMachine.c#255)
> 
> The purpose of that method seems to be to get the main linux thread from which other linux threads of the JVM were spawned from.
> 
> It does this by counting how many children the current pid has, by looking through all files that match `/proc/[0-9]+` in [forEachProcess](http://code.metager.de/source/xref/openjdk/jdk8/jdk/src/solaris/native/sun/tools/attach/LinuxVirtualMachine.c#forEachProcess)
> 
> Of course because the JVM is pid 1, every other process in the docker image has pid 1 as its parent.  So the count of processes with ppid==1 is > 1.
> 
> So the `if` statements at [LinuxVirtualMachine.c#273](http://code.metager.de/source/xref/openjdk/jdk8/jdk/src/solaris/native/sun/tools/attach/LinuxVirtualMachine.c#273) and [LinuxVirtualMachine.c#285](http://code.metager.de/source/xref/openjdk/jdk8/jdk/src/solaris/native/sun/tools/attach/LinuxVirtualMachine.c#285) don't hit, and the C function throws the exception, which is then seen in the stacktrace:
> 
> Any method that eventually calls `sun.tools.attach.LinuxVirtualMachine.<init>` triggers this code path and causes an exception, and the ALPN injection calls this as well as some other JVM cli tools like `jmap` and `jstack`.
