### ISSUE TITLE
Resource staging server errors with large files

### ISSUE THREAD

**Issue by mccheah** [apache-spark-on-k8s/spark#342]
The new submission workflow relies on http uploads and downloads when using the resource staging server. This can run into problems when uploading and downloading large files.

cc @duyanghao

Based on #318 

Stack trace reported when using large files:

```
Exception in thread "main" java.net.SocketTimeoutException: timeout
	at okio.Okio$4.newTimeoutException(Okio.java:227)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:284)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:240)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:325)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:314)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:67)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
	at okhttp3.RealCall.execute(RealCall.java:63)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
	at org.apache.spark.deploy.kubernetes.submit.SubmittedDependencyUploaderImpl.getTypedResponseResult(SubmittedDependencyUploaderImpl.scala:102)
	at org.apache.spark.deploy.kubernetes.submit.SubmittedDependencyUploaderImpl.doUpload(SubmittedDependencyUploaderImpl.scala:98)
	at org.apache.spark.deploy.kubernetes.submit.SubmittedDependencyUploaderImpl.uploadJars(SubmittedDependencyUploaderImpl.scala:71)
	at org.apache.spark.deploy.kubernetes.submit.Client$$anonfun$6.apply(Client.scala:152)
	at org.apache.spark.deploy.kubernetes.submit.Client$$anonfun$6.apply(Client.scala:151)
	at scala.Option.map(Option.scala:146)
	at org.apache.spark.deploy.kubernetes.submit.Client.run(Client.scala:151)
	at org.apache.spark.deploy.kubernetes.submit.Client$$anonfun$run$6.apply(Client.scala:323)
	at org.apache.spark.deploy.kubernetes.submit.Client$$anonfun$run$6.apply(Client.scala:303)
	at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2494)
	at org.apache.spark.deploy.kubernetes.submit.Client$.run(Client.scala:303)
	at org.apache.spark.deploy.kubernetes.submit.Client$.main(Client.scala:264)
	at org.apache.spark.deploy.kubernetes.submit.Client.main(Client.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:757)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:188)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:213)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:127)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:203)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at okio.Okio$2.read(Okio.java:138)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:236)
	... 42 more
```

Looks like we're timing out here and might want to tweak the retrofit client settings, or else make it configurable. But it also might be a problem on the server side.

**Comment by ash211** [comment]
To be fair the old submission workflow also used HTTP when uploading and downloading right?

**Comment by mccheah** [comment]
> To be fair the old submission workflow also used HTTP when uploading and downloading right?

It did, but we ran into the same issues there as well - if not worse because it ran out of heap, which is what #318 reported in the first place.

I'm not sure how much we should be optimizing on large files however. This is an HTTP upload and download, which is inherently non-distributed and will inevitably hit limits, not to mention the limiting factor of the speed of the network. We do gzip-compress the data before sending it over but we can only do so much.

I'm wondering if the better messaging here would be to document a recommendation that the resource staging server should only be used for smaller assets, and that larger assets should be served by distributed storage, network storage, or installing into Docker images.

**Comment by ash211** [comment]
Could add a warning log for uploads larger than a threshold

**Comment by erikerlandson** [comment]
I'd second a documentation-based solution.  Logging a warning message seems useful too, especially if size can be known or estimated after gzip.
