### ISSUE TITLE
Support fractional value (e.g., 0.5) for number of executor cores (spark.executor.cores)

### ISSUE THREAD

**Issue by liyinan926** [apache-spark-on-k8s/spark#359]
Spark only supports integral value for `spark.executor.cores` and will throw a `NumberFormatException` if a fractional value like 0.5 is used. Kubernetes, however, does support requesting a fraction of a CPU core, e.g., 0.1 or 100m. A potential solution is to for Spark to accept a fractional value if running on Kubernetes and round up to 1 otherwise.

**Comment by liyinan926** [comment]
Exception seen in the executor pod:

```
Exception in thread "main" java.lang.NumberFormatException: For input string: "0.5"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:272)
	at scala.collection.immutable.StringOps.toInt(StringOps.scala:29)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend$.main(CoarseGrainedExecutorBackend.scala:258)
	at org.apache.spark.executor.CoarseGrainedExecutorBackend.main(CoarseGrainedExecutorBackend.scala)
```
