### ISSUE TITLE
Spark driver fails with K8s v1.6 out-of-box

### ISSUE THREAD

**Issue by kimoonkim** [apache-spark-on-k8s/spark#448]
Crashes with the following exception:

> Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://kubernetes.default.svc/api/v1/namespaces/default/pods/spark-dfsrw-1503358007989-driver. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. User "system:serviceaccount:default:default" cannot get pods in the namespace "default"..
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:332)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:269)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:241)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:234)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:230)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:745)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:194)
	at org.apache.spark.scheduler.cluster.kubernetes.KubernetesClusterSchedulerBackend.liftedTree1$1(KubernetesClusterSchedulerBackend.scala:142)

It seems this is because the `default` service account does not have pod `edit` privilege any more under RBAC of K8s 1.6. Cluster admins are supposed to give only the barebone capability to the `default` account.

The recommendation is to add another service account, say `spark`, then add the necessary privileges:
```
$ kubectl create serviceaccount spark
$ kubectl create clusterrolebinding spark-edit --clusterrole edit --serviceaccount default:spark --namespace default
```

I did the above and I was hoping to use `--conf spark.kubernetes.authenticate.driver.serviceAccountName=spark`. But it seems the config key is no longer supported?

@foxish @mccheah

**Comment by kimoonkim** [comment]
I have a small patch restoring the support of specifying service account name. Sending a PR soon in case we want a quick fix.

**Comment by ash211** [comment]
Ah, our application uses `spark.kubernetes.authenticate.submission.oauthToken` to authenticate with the apiserver during submission so we didn't see this issue when we upgraded to k8s 1.6 whenever that was.

**Comment by foxish** [comment]
It seems like the service account key exists but isn't being used during pod creation anymore. Thanks for finding this @kimoonkim.
Also, we should document the requirement of a clusterrole and clusterrolebinding when RBAC is enabled.

**Comment by ash211** [comment]
yes, `KUBERNETES_SERVICE_ACCOUNT_NAME` isn't used anymore.  I'd be happy to do a quick review on your PR when you get it in @kimoonkim !

**Comment by kimoonkim** [comment]
Ah, good. Cleaning up the PR a bit. I'll make sure to include the documentation as well.
