### ISSUE TITLE
Executor uses https://kubernetes.default.svc instead of configured master

### ISSUE THREAD

**Issue by yonzhang** [apache-spark-on-k8s/spark#518]
Run v2.2.0-kubernetes-0.4.0 with following command:
bin/spark-submit \
--deploy-mode cluster \
--class org.apache.spark.examples.SparkPi \
--master k8s://https://kube-master-1669894:6443 \
--kubernetes-namespace ns-1 \
--conf spark.executor.instances=1 \
--conf spark.app.name=spark-pi \
--conf spark.kubernetes.driver.docker.image=xx.xx.xx.com/yonzhang/spark-driver:v2.2.0-kubernetes-0.4.0 \
--conf spark.kubernetes.executor.docker.image=xx.xx.xx.com/yonzhang/spar-executor:v2.2.0-kubernetes-0.4.0 \
--conf spark.kubernetes.authenticate.submission.clientKeyFile=/home/yonzhang/client-key-data \
--conf spark.kubernetes.authenticate.submission.clientCertFile=/home/yonzhang/client-certificate-data \
--conf spark.kubernetes.authenticate.submission.caCertFile=/home/yonzhang/certificate-authority-data \
local:///opt/spark/examples/jars/spark-examples_2.11-2.2.0-k8s-0.4.0.jar

And in driver pod, it reports the following error.
2017-10-02 03:20:50 INFO  SparkUI:54 - Bound SparkUI to 0.0.0.0, and started at http://spark-pi-1506914443968-driver-svc.ns-1.svc.cluster.local:4040
2017-10-02 03:20:50 INFO  SparkContext:54 - Added JAR /opt/spark/examples/jars/spark-examples_2.11-2.2.0-k8s-0.4.0.jar at spark://spark-pi-1506914443968-driver-svc.ns-1.svc.cluster.local:7078/jars/spark-examples_2.11-2.2.0-k8s-0.4.0.jar with timestamp 1506914450360
2017-10-02 03:20:50 WARN  KubernetesClusterManager:66 - The executor's init-container config map was not specified. Executors will therefore not attempt to fetch remote or submitted dependencies.
2017-10-02 03:20:50 WARN  KubernetesClusterManager:66 - The executor's init-container config map key was not specified. Executors will therefore not attempt to fetch remote or submitted dependencies.
2017-10-02 03:20:58 ERROR KubernetesClusterSchedulerBackend:91 - Executor cannot find driver pod.
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://kubernetes.default.svc/api/v1/namespaces/ns-1/pods/spark-pi-1506914443968-driver. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. User "system:serviceaccount:ns-1:default" cannot get pods in the namespace "ns-1"..
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:332)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:269)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:241)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:234)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:230)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:745)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:194)
	at org.apache.spark.scheduler.cluster.k8s.KubernetesClusterSchedulerBackend.liftedTree1$1(KubernetesClusterSchedulerBackend.scala:74)
	at org.apache.spark.scheduler.cluster.k8s.KubernetesClusterSchedulerBackend.<init>(KubernetesClusterSchedulerBackend.scala:72)
	at org.apache.spark.scheduler.cluster.k8s.KubernetesClusterManager.createSchedulerBackend(KubernetesClusterManager.scala:139)
	at org.apache.spark.SparkContext$.org$apache$spark$SparkContext$$createTaskScheduler(SparkContext.scala:2764)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:501)
	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2509)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$6.apply(SparkSession.scala:909)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$6.apply(SparkSession.scala:901)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:901)
	at org.apache.spark.examples.SparkPi$.main(SparkPi.scala:31)
	at org.apache.spark.examples.SparkPi.main(SparkPi.scala)

Check with the code of v2.2.0-kubernetes-0.4.0, it uses default api server instead of getting api server from spark.master config.

val kubernetesClient = SparkKubernetesClientFactory.createKubernetesClient(
        **KUBERNETES_MASTER_INTERNAL_URL**,
        Some(sparkConf.get(KUBERNETES_NAMESPACE)),
        APISERVER_AUTH_DRIVER_MOUNTED_CONF_PREFIX,
        sparkConf,
        Some(new File(Config.KUBERNETES_SERVICE_ACCOUNT_TOKEN_PATH)),
        Some(new File(Config.KUBERNETES_SERVICE_ACCOUNT_CA_CRT_PATH)))

Is that a bug or do I miss some configuration?

**Comment by yonzhang** [comment]
Seems it is not an issue. Looking at previous issues, this should be caused by RBAC. Configured RBAC related config, it is fine to create driver pod now.
