### ISSUE TITLE
javax.net.ssl.SSLPeerUnverifiedException: Hostname kubernetes.default.svc not verified

### ISSUE THREAD

**Issue by benni82** [apache-spark-on-k8s/spark#543]
I test spark-on-k8s example in Rancher2.0+Kubernetes1.7

the submit command:
```
bin/spark-submit \
  --deploy-mode cluster \
  --class org.apache.spark.examples.SparkPi \
  --master k8s://http://10.125.4.53:8080/k8s/clusters/1c1 \
  --kubernetes-namespace spark-cluster \
  --conf spark.executor.instances=2 \
  --conf spark.app.name=spark-pi \
  --conf spark.kubernetes.driver.docker.image=kubespark/spark-driver:v2.2.0-kubernetes-0.5.0 \
  --conf spark.kubernetes.executor.docker.image=kubespark/spark-executor:v2.2.0-kubernetes-0.5.0 \
  local:///opt/spark/examples/jars/spark-examples_2.11-2.2.0-k8s-0.5.0.jar 10
```

The excpetion said executor can not find driver:
```
2017-11-06 08:35:59 ERROR KubernetesClusterSchedulerBackend:91 - Executor cannot find driver pod.
io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for kind: [Pod]  with name: [spark-pi-1509957252036-driver]  in namespace: [default]  failed.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:62)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:71)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.getMandatory(BaseOperation.java:228)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:184)
	at org.apache.spark.scheduler.cluster.k8s.KubernetesClusterSchedulerBackend.liftedTree1$1(KubernetesClusterSchedulerBackend.scala:74)
	at org.apache.spark.scheduler.cluster.k8s.KubernetesClusterSchedulerBackend.<init>(KubernetesClusterSchedulerBackend.scala:72)
	at org.apache.spark.scheduler.cluster.k8s.KubernetesClusterManager.createSchedulerBackend(KubernetesClusterManager.scala:142)
	at org.apache.spark.SparkContext$.org$apache$spark$SparkContext$$createTaskScheduler(SparkContext.scala:2764)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:501)
	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2509)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$6.apply(SparkSession.scala:909)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$6.apply(SparkSession.scala:901)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:901)
	at org.apache.spark.examples.SparkPi$.main(SparkPi.scala:31)
	at org.apache.spark.examples.SparkPi.main(SparkPi.scala)
Caused by: javax.net.ssl.SSLPeerUnverifiedException: Hostname kubernetes.default.svc not verified:
    certificate: sha256/k5auE9vDTELZzrNLytslva7wv3dh4VsBLJ0XF6GzJHw=
    DN: CN=kubernetes
    subjectAltNames: [10.43.0.1, 10.43.0.1, kubernetes, kubernetes.kubernetes, kubernetes.kubernetes.rancher.internal]
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:290)
```

**Comment by mccheah** [comment]
This looks like a TLS error that might be specific to the way your cluster is provisioned. It particularly looks like the subject alternative names presented by this API server doesn't have `kubernetes.default.svc`, but we expect to be able to contact the API server with that hostname.

**Comment by mccheah** [comment]
The error message of "Executor cannot find driver pod" is probably misleading here.

**Comment by benni82** [comment]
any env can let Executor use "kubernetes.default" instead of "kubernetes.default.svc"

**Comment by mccheah** [comment]
We don't have the pluggability unfortunately - but given the documentation officially stated by Kubernetes, it seems reasonable to assume that the hostname we're using right now should work. @foxish how often is it the case that Kubernetes clusters set up with kube-dns don't put `kubernetes.default.svc` in the certificate's SANs?

**Comment by burgerdev** [comment]
Hi @mccheah,

could you please clarify where the documentation states that `kubernetes.default.svc` is the go-to API server? As far as I understand, this address is only the right place to go if

1. kube-dns is installed
2. a service named `kubernetes` is deployed to namespace `default`
3. this service is reachable from the driver pod

(1) is a requirement anyways, did I get this right? However, I don't see why (2) or (3) could be expected. There might not even be a namespace `default`, and even if it's there, it might be isolated from the driver's namespace (e.g. by network policy). It would be really helpful if we had either a spark property to set the master, or if we could fall back to the client libraries mechanism (env var `KUBERNETES_MASTER` was suggested in #558).

Would it be ok to open a PR for this?

P.S.: For reference, rancher/rancher#10086 is the rancher bug @benni82 and I ran into.

**Comment by mccheah** [comment]
See https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/

> While running in a Pod, the Kubernetes apiserver is accessible via a Service named kubernetes in the default namespace. Therefore, Pods can use the kubernetes.default hostname to query the API server. Official client libraries do this automatically.

Nevertheless I'm not sure as to how often this is not the case in practice. @foxish can you weigh in here?

**Comment by burgerdev** [comment]
Thanks for the link, I missed that part. I'm still curious if people deploy network policies to jail pods to their namespaces, and if inability to access k8s api is intentional in those cases.

**Comment by foxish** [comment]
> Thanks for the link, I missed that part. I'm still curious if people deploy network policies to jail pods to their namespaces, and if inability to access k8s api is intentional in those cases.

I don't think that it's common. The accessibility of `kubernetes.default` from pods should be covered by K8s conformance, so, it should work on **any conformant cluster**. For example, see https://github.com/cncf/k8s-conformance/blob/master/v1.7/gke/e2e.log. 

```
[k8s.io] DNS 
  should provide DNS for the cluster [Conformance]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/dns.go:341
[BeforeEach] [k8s.io] DNS
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:130
STEP: Creating a kubernetes client
Nov  2 17:50:02.291: INFO: >>> kubeConfig: 
STEP: Building a namespace api object
STEP: Waiting for a default service account to be provisioned in namespace
[It] should provide DNS for the cluster [Conformance]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/dns.go:341
STEP: Running these commands on wheezy: for i in `seq 1 600`; do test -n "$$(dig +notcp +noall +answer +search kubernetes.default A)" && echo OK > /results/wheezy_udp@kubernetes.default;test -n "$$(dig +tcp +noall +answer +search kubernetes.default A)" && echo OK > /results/wheezy_tcp@kubernetes.default;test -n "$$(dig +notcp +noall +answer +search kubernetes.default.svc A)" && echo OK > /results/wheezy_udp@kubernetes.default.svc;test -n "$$(dig +tcp +noall +answer +search kubernetes.default.svc A)" && echo OK > /results/wheezy_tcp@kubernetes.default.svc;test -n "$$(dig +notcp +noall +answer +search kubernetes.default.svc.cluster.local A)" && echo OK > /results/wheezy_udp@kubernetes.default.svc.cluster.local;test -n "$$(dig +tcp +noall +answer +search kubernetes.default.svc.cluster.local A)" && echo OK > /results/wheezy_tcp@kubernetes.default.svc.cluster.local;test -n "$$(getent hosts dns-querier-1.dns-test-service.e2e-tests-dns-dntwb.svc.cluster.local)" && echo OK > /results/wheezy_hosts@dns-querier-1.dns-test-service.e2e-tests-dns-dntwb.svc.cluster.local;test -n "$$(getent hosts dns-querier-1)" && echo OK > /results/wheezy_hosts@dns-querier-1;podARec=$$(hostname -i| awk -F. '{print $$1"-"$$2"-"$$3"-"$$4".e2e-tests-dns-dntwb.pod.cluster.local"}');test -n "$$(dig +notcp +noall +answer +search $${podARec} A)" && echo OK > /results/wheezy_udp@PodARecord;test -n "$$(dig +tcp +noall +answer +search $${podARec} A)" && echo OK > /results/wheezy_tcp@PodARecord;sleep 1; done

STEP: Running these commands on jessie: for i in `seq 1 600`; do test -n "$$(dig +notcp +noall +answer +search kubernetes.default A)" && echo OK > /results/jessie_udp@kubernetes.default;test -n "$$(dig +tcp +noall +answer +search kubernetes.default A)" && echo OK > /results/jessie_tcp@kubernetes.default;test -n "$$(dig +notcp +noall +answer +search kubernetes.default.svc A)" && echo OK > /results/jessie_udp@kubernetes.default.svc;test -n "$$(dig +tcp +noall +answer +search kubernetes.default.svc A)" && echo OK > /results/jessie_tcp@kubernetes.default.svc;test -n "$$(dig +notcp +noall +answer +search kubernetes.default.svc.cluster.local A)" && echo OK > /results/jessie_udp@kubernetes.default.svc.cluster.local;test -n "$$(dig +tcp +noall +answer +search kubernetes.default.svc.cluster.local A)" && echo OK > /results/jessie_tcp@kubernetes.default.svc.cluster.local;test -n "$$(getent hosts dns-querier-1.dns-test-service.e2e-tests-dns-dntwb.svc.cluster.local)" && echo OK > /results/jessie_hosts@dns-querier-1.dns-test-service.e2e-tests-dns-dntwb.svc.cluster.local;test -n "$$(getent hosts dns-querier-1)" && echo OK > /results/jessie_hosts@dns-querier-1;podARec=$$(hostname -i| awk -F. '{print $$1"-"$$2"-"$$3"-"$$4".e2e-tests-dns-dntwb.pod.cluster.local"}');test -n "$$(dig +notcp +noall +answer +search $${podARec} A)" && echo OK > /results/jessie_udp@PodARecord;test -n "$$(dig +tcp +noall +answer +search $${podARec} A)" && echo OK > /results/jessie_tcp@PodARecord;sleep 1; done

STEP: creating a pod to probe DNS
STEP: submitting the pod to kubernetes
STEP: retrieving the pod
STEP: looking for the results for each expected name from probers
Nov  2 17:50:14.555: INFO: DNS probes using dns-test-408af781-bff6-11e7-8c89-0a580a3c001b succeeded
```

**Comment by burgerdev** [comment]
Thanks @foxish for clarifying this. Need to bring this to rancher's attention, then.
