### ISSUE TITLE
Multi-stage job fails with "Message: object is being deleted: pods "heatmap-1510360645152-exec-1" already exists."

### ISSUE THREAD

**Issue by timfpark** [apache-spark-on-k8s/spark#548]
It looks like the K8s scheduler might be reusing pod names between stages of a job such that when it goes to recreate the executor pod in the next stage it fails with "object is being deleted: pods "heatmap-1510360645152-exec-1".   (Am I understanding the log below correctly?)

This is with spark-driver-py:v2.2.0-kubernetes-0.5.0 and spark-executor-py:v2.2.0-kubernetes-0.5.0 and static allocation and following submit command:

```
bin/spark-submit \
  --deploy-mode cluster \
  --master k8s://https://spark-dwr-cluster.eastus2.cloudapp.azure.com \
  --kubernetes-namespace heatmap \
  --conf spark.executor.instances=32 \
  --conf spark.app.name=heatmap \
  --conf spark.kubernetes.driver.docker.image=timfpark/heatmap-driver:v5 \
  --conf spark.kubernetes.executor.docker.image=timfpark/heatmap-executor:v5 \
  --jars local:///opt/spark/code/spark-cassandra-connector-2.0.5-s_2.11.jar \
  --py-files local:///opt/spark/code/tile.py \
  local:///opt/spark/code/heatmap.py
```

```
2017-11-11 00:38:04 INFO  SparkUI:54 - Bound SparkUI to 0.0.0.0, and started at http://heatmap-1510360645152-driver-svc.heatmap.svc.cluster.local:4040
2017-11-11 00:38:04 INFO  SparkContext:54 - Added JAR /opt/spark/code/spark-cassandra-connector-2.0.5-s_2.11.jar at spark://heatmap-1510360645152-driver-svc.heatmap.svc.cluster.local:7078/jars/spark-cassandra-connector-2.0.5-s_2.11.jar with timestamp 1510360684660
2017-11-11 00:38:04 INFO  SparkContext:54 - Added file /opt/spark/code/heatmap.py at spark://heatmap-1510360645152-driver-svc.heatmap.svc.cluster.local:7078/files/heatmap.py with timestamp 1510360684661
2017-11-11 00:38:04 INFO  Utils:54 - Copying /opt/spark/code/heatmap.py to /mnt/tmp/spark-local/spark-c66635b1-d3aa-46fb-bc5c-2de08eeb983d/spark-bc88635c-914e-4dc5-ba6d-378ecba667f9/userFiles-0f323163-2588-40cc-a697-119a911699ff/heatmap.py
2017-11-11 00:38:04 INFO  SparkContext:54 - Added file /opt/spark/code/tile.py at spark://heatmap-1510360645152-driver-svc.heatmap.svc.cluster.local:7078/files/tile.py with timestamp 1510360684674
2017-11-11 00:38:04 INFO  Utils:54 - Copying /opt/spark/code/tile.py to /mnt/tmp/spark-local/spark-c66635b1-d3aa-46fb-bc5c-2de08eeb983d/spark-bc88635c-914e-4dc5-ba6d-378ecba667f9/userFiles-0f323163-2588-40cc-a697-119a911699ff/tile.py
2017-11-11 00:38:04 WARN  KubernetesClusterManager:66 - The executor's init-container config map was not specified. Executors will therefore not attempt to fetch remote or submitted dependencies.
2017-11-11 00:38:04 WARN  KubernetesClusterManager:66 - The executor's init-container config map key was not specified. Executors will therefore not attempt to fetch remote or submitted dependencies.
2017-11-11 00:38:04 INFO  Utils:54 - Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 7079.
2017-11-11 00:38:04 INFO  NettyBlockTransferService:54 - Server created on heatmap-1510360645152-driver-svc.heatmap.svc.cluster.local:7079
2017-11-11 00:38:04 INFO  BlockManager:54 - Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
2017-11-11 00:38:04 INFO  BlockManagerMaster:54 - Registering BlockManager BlockManagerId(driver, heatmap-1510360645152-driver-svc.heatmap.svc.cluster.local, 7079, None)
2017-11-11 00:38:04 INFO  BlockManagerMasterEndpoint:54 - Registering block manager heatmap-1510360645152-driver-svc.heatmap.svc.cluster.local:7079 with 408.9 MB RAM, BlockManagerId(driver, heatmap-1510360645152-driver-svc.heatmap.svc.cluster.local, 7079, None)
2017-11-11 00:38:04 INFO  BlockManagerMaster:54 - Registered BlockManager BlockManagerId(driver, heatmap-1510360645152-driver-svc.heatmap.svc.cluster.local, 7079, None)
2017-11-11 00:38:04 INFO  BlockManager:54 - Initialized BlockManager: BlockManagerId(driver, heatmap-1510360645152-driver-svc.heatmap.svc.cluster.local, 7079, None)
2017-11-11 00:38:04 INFO  ContextHandler:781 - Started o.s.j.s.ServletContextHandler@7abe9f6f{/metrics/json,null,AVAILABLE,@Spark}
2017-11-11 00:38:05 INFO  KubernetesClusterSchedulerBackend:54 - Received delete pod heatmap-1510360645152-exec-24 event. Reason: null
2017-11-11 00:38:05 INFO  KubernetesClusterSchedulerBackend:54 - Received delete pod heatmap-1510360645152-exec-20 event. Reason: null
2017-11-11 00:38:05 INFO  KubernetesClusterSchedulerBackend:54 - Received delete pod heatmap-1510360645152-exec-33 event. Reason: null
2017-11-11 00:38:05 INFO  KubernetesClusterSchedulerBackend:54 - Received delete pod heatmap-1510360645152-exec-5 event. Reason: null
2017-11-11 00:38:05 ERROR KubernetesClusterSchedulerBackend:91 - Failed to allocate executor pod.
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://kubernetes.default.svc/api/v1/namespaces/heatmap/pods. Message: object is being deleted: pods "heatmap-1510360645152-exec-1" already exists. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=null, kind=pods, name=heatmap-1510360645152-exec-1, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=object is being deleted: pods "heatmap-1510360645152-exec-1" already exists, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:470)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:409)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:343)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:226)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:769)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:356)
	at org.apache.spark.scheduler.cluster.k8s.KubernetesClusterSchedulerBackend.org$apache$spark$scheduler$cluster$k8s$KubernetesClusterSchedulerBackend$$allocateNewExecutorPod(KubernetesClusterSchedulerBackend.scala:293)
	at org.apache.spark.scheduler.cluster.k8s.KubernetesClusterSchedulerBackend$$anon$2$$anonfun$run$1.apply$mcVI$sp(KubernetesClusterSchedulerBackend.scala:125)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at org.apache.spark.scheduler.cluster.k8s.KubernetesClusterSchedulerBackend$$anon$2.run(KubernetesClusterSchedulerBackend.scala:123)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
2017-11-11 00:38:06 INFO  KubernetesClusterSchedulerBackend:54 - Received delete pod heatmap-1510360645152-exec-6 event. Reason: null
2017-11-11 00:38:06 INFO  KubernetesClusterSchedulerBackend:54 - Received delete pod heatmap-1510360645152-exec-7 event. Reason: null
2017-11-11 00:38:06 INFO  KubernetesClusterSchedulerBackend:54 - Received delete pod heatmap-1510360645152-exec-15 event. Reason: null
2017-11-11 00:38:06 INFO  KubernetesClusterSchedulerBackend:54 - Received delete pod heatmap-1510360645152-exec-30 event. Reason: null
2017-11-11 00:38:06 INFO  KubernetesClusterSchedulerBackend:54 - Received delete pod heatmap-1510360645152-exec-22 event. Reason: null
2017-11-11 00:38:07 INFO  KubernetesClusterSchedulerBackend:54 - Received delete pod heatmap-1510360645152-exec-1 event. Reason: null
2017-11-11 00:38:07 INFO  KubernetesClusterSchedulerBackend:54 - Received delete pod heatmap-1510360645152-exec-2 event. Reason: null
2017-11-11 00:38:07 INFO  KubernetesClusterSchedulerBackend:54 - Received delete pod heatmap-1510360645152-exec-17 event. Reason: null
2017-11-11 00:38:07 INFO  KubernetesClusterSchedulerBackend:54 - Received delete pod heatmap-1510360645152-exec-12 event. Reason: null
```

**Comment by foxish** [comment]
Ah.. this is definitely something we should allow for with dynamic allocation. 
cc @apache-spark-on-k8s/contributors @liyinan926
