### ISSUE TITLE
Can not run spark-pi in minikube 

### ISSUE THREAD

**Issue by zjffdu** [apache-spark-on-k8s/spark#555]
Sorry, if this is not the right place ask this kind of question.

I try to run spark-pi in minikube which is installed in my local box. But this job is never finished.

I see the following log infinitely.

```
status: [ContainerStatus(containerID=null, image=kubespark/spark-driver:v2.2.0-kubernetes-0.5.0, imageID=, lastState=ContainerState(running=null, terminated=null, waiting=null, additionalProperties={}), name=spark-kubernetes-driver, ready=false, restartCount=0, state=ContainerState(running=null, terminated=null, waiting=ContainerStateWaiting(message=null, reason=PodInitializing, additionalProperties={}), additionalProperties={}), additionalProperties={})]
2017-11-20 11:14:55 INFO  LoggingPodStatusWatcherImpl:54 - State changed, new state:
	 pod name: spark-pi-1511144113329-driver
	 namespace: default
	 labels: spark-app-selector -> spark-52e5c8d833874d9eb53560e264115f45, spark-role -> driver
	 pod uid: aa75f718-cd98-11e7-981a-0800279ad17d
	 creation time: 2017-11-20T02:15:23Z
	 service account name: default
	 volumes: spark-local-dir-0-spark-05d24ca3-5f30-4719-82b9-c2142865f0a8, spark-init-properties, download-jars-volume, download-files, spark-init-secret, default-token-2k62j
	 node name: minikube
	 start time: 2017-11-20T02:15:23Z
	 container images: kubespark/spark-driver:v2.2.0-kubernetes-0.5.0
	 phase: Pending
	 status: [ContainerStatus(containerID=null, image=kubespark/spark-driver:v2.2.0-kubernetes-0.5.0, imageID=, lastState=ContainerState(running=null, terminated=null, waiting=null, additionalProperties={}), name=spark-kubernetes-driver, ready=false, restartCount=0, state=ContainerState(running=null, terminated=null, waiting=ContainerStateWaiting(message=null, reason=PodInitializing, additionalProperties={}), additionalProperties={}), additionalProperties={})]
2017-11-20 11:15:07 INFO  LoggingPodStatusWatcherImpl:54 - State changed, new state:
	 pod name: spark-pi-1511144113329-driver
	 namespace: default
	 labels: spark-app-selector -> spark-52e5c8d833874d9eb53560e264115f45, spark-role -> driver
	 pod uid: aa75f718-cd98-11e7-981a-0800279ad17d
	 creation time: 2017-11-20T02:15:23Z
	 service account name: default
	 volumes: spark-local-dir-0-spark-05d24ca3-5f30-4719-82b9-c2142865f0a8, spark-init-properties, download-jars-volume, download-files, spark-init-secret, default-token-2k62j
	 node name: minikube
	 start time: 2017-11-20T02:15:23Z
	 container images: kubespark/spark-driver:v2.2.0-kubernetes-0.5.0
	 phase: Pending
```

And this is the command I use to submit job

```
bin/spark-submit   --deploy-mode cluster   --class org.apache.spark.examples.SparkPi   --master k8s://https://192.168.99.100:8443   --kubernetes-namespace default   --conf spark.executor.instances=5   --conf spark.app.name=spark-pi   --conf spark.kubernetes.driver.docker.image=kubespark/spark-driver:v2.2.0-kubernetes-0.5.0   --conf spark.kubernetes.executor.docker.image=kubespark/spark-executor:v2.2.0-kubernetes-0.5.0 --conf spark.kubernetes.resourceStagingServer.uri=http://192.168.99.100:31000  examples/target/original-spark-examples_2.11-2.2.0-k8s-0.5.0.jar
```

Is there anything I did wrong ? Thanks

**Comment by foxish** [comment]
Can you do `kubectl get pods` and post the output? It could be that it is unable to schedule all pods.

**Comment by zjffdu** [comment]
Here's the output

```
NAME                                             READY     STATUS                  RESTARTS   AGE
kubernetes-bootcamp-6c74779b45-m2s25             1/1       Running                 2          13d
spark-pi-1511144113329-driver                    0/1       Init:ImagePullBackOff   0          1h
spark-resource-staging-server-6bcc9fb55f-gjwf5   1/1       Running                 0          2h
```

**Comment by foxish** [comment]
It looks like the init container image is not specified/incorrectly specified. On the other hand, for spark-pi, you don't need the staging server, or the init container. Can you try again without specifying it?

**Comment by geraldstanje** [comment]
@foxish i tried to run the same example with your suggestions but got the following error. any idea?
```
$ kubectl cluster-info
Kubernetes master is running at https://192.168.99.100:8443

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```

script to start it:
```
k8s_apiserver_host="192.168.99.100"
k8s_apiserver_port="8443"
cwd=`pwd`

echo $k8s_apiserver_host
echo $k8s_apiserver_port
echo $cwd

spark/bin/spark-submit \
  --deploy-mode cluster \
  --class org.apache.spark.examples.SparkPi \
  --master k8s://https://$k8s_apiserver_host:$k8s_apiserver_port \
  --kubernetes-namespace default \
  --conf spark.executor.instances=5 \
  --conf spark.app.name=spark-pi \
  --conf spark.kubernetes.driver.docker.image=kubespark/spark-driver:v2.2.0-kubernetes-0.5.0 \
  --conf spark.kubernetes.executor.docker.image=kubespark/spark-executor:v2.2.0-kubernetes-0.5.0 \
  spark/examples/target/scala-2.11/jars/spark-examples_2.11-2.2.0-k8s-0.5.0.jar
```

get this error:
```
$ ./run.sh 
192.168.99.100
8443
/Users/geri/run_spark_on_k8s
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: Local JARs were provided, however no resource staging server URI was found.
	at scala.Predef$.require(Predef.scala:224)
	at org.apache.spark.deploy.k8s.OptionRequirements$$anonfun$requireSecondIfFirstIsDefined$1.apply(OptionRequirements.scala:33)
	at org.apache.spark.deploy.k8s.OptionRequirements$$anonfun$requireSecondIfFirstIsDefined$1.apply(OptionRequirements.scala:32)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.deploy.k8s.OptionRequirements$.requireSecondIfFirstIsDefined(OptionRequirements.scala:32)
	at org.apache.spark.deploy.k8s.submit.submitsteps.initcontainer.InitContainerConfigurationStepsOrchestrator.<init>(InitContainerConfigurationStepsOrchestrator.scala:66)
	at org.apache.spark.deploy.k8s.submit.DriverConfigurationStepsOrchestrator.getAllConfigurationSteps(DriverConfigurationStepsOrchestrator.scala:175)
	at org.apache.spark.deploy.k8s.submit.Client$$anonfun$run$5.apply(Client.scala:195)
	at org.apache.spark.deploy.k8s.submit.Client$$anonfun$run$5.apply(Client.scala:193)
	at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2551)
	at org.apache.spark.deploy.k8s.submit.Client$.run(Client.scala:193)
	at org.apache.spark.deploy.k8s.submit.Client$.main(Client.scala:213)
	at org.apache.spark.deploy.k8s.submit.Client.main(Client.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:786)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by liyinan926** [comment]
@geraldstanje this is because `spark/examples/target/scala-2.11/jars/spark-examples_2.11-2.2.0-k8s-0.5.0.jar` is considered a submission client local file that needs to be staged through the resource staging server. You should use `local:///opt/spark/examples/jars/spark-examples_2.11-2.2.0-k8s-0.5.0.jar`.

**Comment by geraldstanje** [comment]
To run the resource staging server with default configurations, the Kubernetes resources can be created:
```
kubectl create -f conf/kubernetes-resource-staging-server.yaml
```

added the staging server:
```
--conf spark.kubernetes.initcontainer.docker.image=kubespark/spark-init:v2.2.0-kubernetes-0.5.0 \
--conf spark.kubernetes.resourceStagingServer.uri=http://192.168.99.100:31000 \
```

get authentication error, how can you edit and fix the permission issue?
```
2017-12-31 12:57:53 INFO  SecurityManager:54 - Changing view acls to: geri
2017-12-31 12:57:53 INFO  SecurityManager:54 - Changing modify acls to: geri
2017-12-31 12:57:53 INFO  SecurityManager:54 - Changing view acls groups to: 
2017-12-31 12:57:53 INFO  SecurityManager:54 - Changing modify acls groups to: 
2017-12-31 12:57:53 INFO  SecurityManager:54 - SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(geri); groups with view permissions: Set(); users  with modify permissions: Set(geri); groups with modify permissions: Set()
Exception in thread "main" java.net.ConnectException: Failed to connect to /192.168.99.100:31000
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:225)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:149)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:195)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
	at org.apache.spark.deploy.k8s.submit.SubmittedDependencyUploaderImpl.getTypedResponseResult(SubmittedDependencyUploaderImpl.scala:101)
	at org.apache.spark.deploy.k8s.submit.SubmittedDependencyUploaderImpl.doUpload(SubmittedDependencyUploaderImpl.scala:97)
	at org.apache.spark.deploy.k8s.submit.SubmittedDependencyUploaderImpl.uploadJars(SubmittedDependencyUploaderImpl.scala:70)
	at org.apache.spark.deploy.k8s.submit.submitsteps.initcontainer.SubmittedResourcesInitContainerConfigurationStep.configureInitContainer(SubmittedResourcesInitContainerConfigurationStep.scala:48)
	at org.apache.spark.deploy.k8s.submit.submitsteps.InitContainerBootstrapStep$$anonfun$configureDriver$1.apply(InitContainerBootstrapStep.scala:43)
	at org.apache.spark.deploy.k8s.submit.submitsteps.InitContainerBootstrapStep$$anonfun$configureDriver$1.apply(InitContainerBootstrapStep.scala:42)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.apache.spark.deploy.k8s.submit.submitsteps.InitContainerBootstrapStep.configureDriver(InitContainerBootstrapStep.scala:42)
	at org.apache.spark.deploy.k8s.submit.Client$$anonfun$run$1.apply(Client.scala:102)
	at org.apache.spark.deploy.k8s.submit.Client$$anonfun$run$1.apply(Client.scala:101)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.apache.spark.deploy.k8s.submit.Client.run(Client.scala:101)
	at org.apache.spark.deploy.k8s.submit.Client$$anonfun$run$5.apply(Client.scala:200)
	at org.apache.spark.deploy.k8s.submit.Client$$anonfun$run$5.apply(Client.scala:193)
	at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2551)
	at org.apache.spark.deploy.k8s.submit.Client$.run(Client.scala:193)
	at org.apache.spark.deploy.k8s.submit.Client$.main(Client.scala:213)
	at org.apache.spark.deploy.k8s.submit.Client.main(Client.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:786)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:124)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:223)
	... 45 more
2017-12-31 12:57:53 INFO  ShutdownHookManager:54 - Shutdown hook called
2017-12-31 12:57:53 INFO  ShutdownHookManager:54 - Deleting directory /private/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/uploaded-jars-5a8164cc-e0d0-4d54-a01e-d8bdc0f6f175
```

**Comment by geraldstanje** [comment]
seems i had to wait a bit for the spark-resource-staging-server to be running:

now i call spark-submit but it application hangs here, any idea why?
```
2017-12-31 13:45:03 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2017-12-31 13:45:03 INFO  SecurityManager:54 - Changing view acls to: geri
2017-12-31 13:45:03 INFO  SecurityManager:54 - Changing modify acls to: geri
2017-12-31 13:45:03 INFO  SecurityManager:54 - Changing view acls groups to: 
2017-12-31 13:45:03 INFO  SecurityManager:54 - Changing modify acls groups to: 
2017-12-31 13:45:03 INFO  SecurityManager:54 - SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(geri); groups with view permissions: Set(); users  with modify permissions: Set(geri); groups with modify permissions: Set()
2017-12-31 13:45:17 INFO  LoggingPodStatusWatcherImpl:54 - State changed, new state: 
	 pod name: spark-pi-1514745902976-driver
	 namespace: default
	 labels: spark-app-selector -> spark-968699f0a817477a81b20ae8853c9930, spark-role -> driver
	 pod uid: bea70f42-ee5a-11e7-91fa-08002718fe97
	 creation time: 2017-12-31T18:45:17Z
	 service account name: default
	 volumes: spark-local-dir-0-spark-725d0c37-8675-4de2-b238-4c8819d205f1, spark-init-properties, download-jars-volume, download-files, spark-init-secret, default-token-nxcnb
	 node name: N/A
	 start time: N/A
	 container images: N/A
	 phase: Pending
	 status: []
2017-12-31 13:45:17 INFO  LoggingPodStatusWatcherImpl:54 - State changed, new state: 
	 pod name: spark-pi-1514745902976-driver
	 namespace: default
	 labels: spark-app-selector -> spark-968699f0a817477a81b20ae8853c9930, spark-role -> driver
	 pod uid: bea70f42-ee5a-11e7-91fa-08002718fe97
	 creation time: 2017-12-31T18:45:17Z
	 service account name: default
	 volumes: spark-local-dir-0-spark-725d0c37-8675-4de2-b238-4c8819d205f1, spark-init-properties, download-jars-volume, download-files, spark-init-secret, default-token-nxcnb
	 node name: minikube
	 start time: N/A
	 container images: N/A
	 phase: Pending
	 status: []
2017-12-31 13:45:17 INFO  LoggingPodStatusWatcherImpl:54 - State changed, new state: 
	 pod name: spark-pi-1514745902976-driver
	 namespace: default
	 labels: spark-app-selector -> spark-968699f0a817477a81b20ae8853c9930, spark-role -> driver
	 pod uid: bea70f42-ee5a-11e7-91fa-08002718fe97
	 creation time: 2017-12-31T18:45:17Z
	 service account name: default
	 volumes: spark-local-dir-0-spark-725d0c37-8675-4de2-b238-4c8819d205f1, spark-init-properties, download-jars-volume, download-files, spark-init-secret, default-token-nxcnb
	 node name: minikube
	 start time: 2017-12-31T18:45:17Z
	 container images: kubespark/spark-driver:v2.2.0-kubernetes-0.5.0
	 phase: Pending
	 status: [ContainerStatus(containerID=null, image=kubespark/spark-driver:v2.2.0-kubernetes-0.5.0, imageID=, lastState=ContainerState(running=null, terminated=null, waiting=null, additionalProperties={}), name=spark-kubernetes-driver, ready=false, restartCount=0, state=ContainerState(running=null, terminated=null, waiting=ContainerStateWaiting(message=null, reason=PodInitializing, additionalProperties={}), additionalProperties={}), additionalProperties={})]
2017-12-31 13:45:17 INFO  Client:54 - Waiting for application spark-pi to finish...
2017-12-31 13:45:24 INFO  LoggingPodStatusWatcherImpl:54 - State changed, new state: 
	 pod name: spark-pi-1514745902976-driver
	 namespace: default
	 labels: spark-app-selector -> spark-968699f0a817477a81b20ae8853c9930, spark-role -> driver
	 pod uid: bea70f42-ee5a-11e7-91fa-08002718fe97
	 creation time: 2017-12-31T18:45:17Z
	 service account name: default
	 volumes: spark-local-dir-0-spark-725d0c37-8675-4de2-b238-4c8819d205f1, spark-init-properties, download-jars-volume, download-files, spark-init-secret, default-token-nxcnb
	 node name: minikube
	 start time: 2017-12-31T18:45:17Z
	 container images: kubespark/spark-driver:v2.2.0-kubernetes-0.5.0
	 phase: Pending
	 status: [ContainerStatus(containerID=null, image=kubespark/spark-driver:v2.2.0-kubernetes-0.5.0, imageID=, lastState=ContainerState(running=null, terminated=null, waiting=null, additionalProperties={}), name=spark-kubernetes-driver, ready=false, restartCount=0, state=ContainerState(running=null, terminated=null, waiting=ContainerStateWaiting(message=null, reason=PodInitializing, additionalProperties={}), additionalProperties={}), additionalProperties={})]
2017-12-31 13:45:27 INFO  LoggingPodStatusWatcherImpl:54 - State changed, new state: 
	 pod name: spark-pi-1514745902976-driver
	 namespace: default
	 labels: spark-app-selector -> spark-968699f0a817477a81b20ae8853c9930, spark-role -> driver
	 pod uid: bea70f42-ee5a-11e7-91fa-08002718fe97
	 creation time: 2017-12-31T18:45:17Z
	 service account name: default
	 volumes: spark-local-dir-0-spark-725d0c37-8675-4de2-b238-4c8819d205f1, spark-init-properties, download-jars-volume, download-files, spark-init-secret, default-token-nxcnb
	 node name: minikube
	 start time: 2017-12-31T18:45:17Z
	 container images: kubespark/spark-driver:v2.2.0-kubernetes-0.5.0
	 phase: Pending
	 status: [ContainerStatus(containerID=null, image=kubespark/spark-driver:v2.2.0-kubernetes-0.5.0, imageID=, lastState=ContainerState(running=null, terminated=null, waiting=null, additionalProperties={}), name=spark-kubernetes-driver, ready=false, restartCount=0, state=ContainerState(running=null, terminated=null, waiting=ContainerStateWaiting(message=null, reason=PodInitializing, additionalProperties={}), additionalProperties={}), additionalProperties={})]
2017-12-31 13:45:28 INFO  LoggingPodStatusWatcherImpl:54 - State changed, new state: 
	 pod name: spark-pi-1514745902976-driver
	 namespace: default
	 labels: spark-app-selector -> spark-968699f0a817477a81b20ae8853c9930, spark-role -> driver
	 pod uid: bea70f42-ee5a-11e7-91fa-08002718fe97
	 creation time: 2017-12-31T18:45:17Z
	 service account name: default
	 volumes: spark-local-dir-0-spark-725d0c37-8675-4de2-b238-4c8819d205f1, spark-init-properties, download-jars-volume, download-files, spark-init-secret, default-token-nxcnb
	 node name: minikube
	 start time: 2017-12-31T18:45:17Z
	 container images: kubespark/spark-driver:v2.2.0-kubernetes-0.5.0
	 phase: Running
	 status: [ContainerStatus(containerID=docker://77c748be7aaa3a0b91015d0f0c2046237910241e4f49e4376ee1d17cc7cd4119, image=kubespark/spark-driver:v2.2.0-kubernetes-0.5.0, imageID=docker-pullable://kubespark/spark-driver@sha256:7539c28c4dbfc55addf5c3f439d26b964c4b04cd780a066c708242867356eb0b, lastState=ContainerState(running=null, terminated=null, waiting=null, additionalProperties={}), name=spark-kubernetes-driver, ready=true, restartCount=0, state=ContainerState(running=ContainerStateRunning(startedAt=Time(time=2017-12-31T18:45:27Z, additionalProperties={}), additionalProperties={}), terminated=null, waiting=null, additionalProperties={}), additionalProperties={})]
```

kubectl get pods:
```
Every 2.0s: kubectl get pods                                                                        MM-MAC-3270: Sun Dec 31 13:46:45 2017

NAME                                             READY     STATUS    RESTARTS   AGE
spark-pi-1514745902976-driver                    1/1       Running   0          9m
spark-pi-1514745902976-exec-1                    0/1       Pending   0          9m
spark-pi-1514745902976-exec-2                    0/1       Pending   0          9m
spark-pi-1514745902976-exec-3                    0/1       Pending   0          9m
spark-pi-1514745902976-exec-4                    0/1       Pending   0          9m
spark-pi-1514745902976-exec-5                    0/1       Pending   0          9m
spark-resource-staging-server-6bcc9fb55f-pfn8f   1/1       Running   0          12m
```

spark-submit command:
```
bin/spark-submit \
  --deploy-mode cluster \
  --class org.apache.spark.examples.SparkPi \
  --master k8s://https://192.168.99.100:8443 \
  --kubernetes-namespace default \
  --conf spark.executor.instances=5 \
  --conf spark.app.name=spark-pi \
  --conf spark.kubernetes.driver.docker.image=kubespark/spark-driver:v2.2.0-kubernetes-0.5.0 \
  --conf spark.kubernetes.executor.docker.image=kubespark/spark-executor:v2.2.0-kubernetes-0.5.0 \
  --conf spark.kubernetes.initcontainer.docker.image=kubespark/spark-init:v2.2.0-kubernetes-0.5.0 \
  --conf spark.kubernetes.resourceStagingServer.uri=http://192.168.99.100:31000 \
  ./examples/target/scala-2.11/jars/spark-examples_2.11-2.2.0-k8s-0.5.0.jar
```

**Comment by foxish** [comment]
@geraldstanje it might just be lack of resources if everything else is pending. One way might be giving minikube more memory/cpu when it starts up using the relevant flags.

**Comment by geraldstanje** [comment]
@foxish you are right, that was the issue. when i increase the number of cpus and memory it works fine.

e.g.:
```
minikube delete; minikube start --cpus 7 --memory 8096
```

i think @zjffdu issue is related to this.
