### ISSUE TITLE
Replace manual ping from the client with a liveness probe

### ISSUE THREAD

**Issue by mccheah** [apache-spark-on-k8s/spark#72]
Currently the `Client` pings the submission server to verify the Java process has started and is accepting connections, before moving forward to upload the data to the server.

We could look into using Kubernetes primitives to make the client-side ping unnecessary. The Watch is currently reporting back the pod's status, but while the Watch reports the pod as created and the container as started, the Java server has not finished initializing necessarily at that point. It would be beneficial if the Watch was more accurate in regards to whether or not the REST server is actually ready. That being said it's unclear what Kubernetes primitives could be used here. Perhaps an intelligent usage of [liveness probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/) could be something to look into.

**Comment by mccheah** [comment]
@foxish is there something in Kubernetes here that would be helpful for this situation?

**Comment by foxish** [comment]
[ReadinessProbes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#defining-readiness-probes) sound like what we want here. We can check the readiness condition on the Pod before sending it any requests. 

* Liveness is used to answer the question: is my pod somehow broken? Should I restart it?
* Readiness is used to answer: Is my pod ready to serve traffic?

Additionally, a service will not serve traffic to "unready" pods.

**Comment by ash211** [comment]
Or maybe the JVM rest server process could set a label on its own pod when
it's ready and the submitter has a Watch for that label being added?

**Comment by foxish** [comment]
A pod modifying its own labels/attributes is a pattern that is discouraged generally, as it makes it hard to reason about changes to the spec.

**Comment by ash211** [comment]
Do pod readiness state changes get propagated through the watch API? If so
that seems like a great use to avoid the ping retry pattern we have now

**Comment by foxish** [comment]
If we're watching for modifications, we should see one, and a new `condition` added to the `.Spec.status`.

```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2017-02-02T00:26:40Z
    status: "True"
    type: Ready
```

**Comment by iyanuobidele** [comment]
You just beat me to this.

The SparkJob fails, when interrrupted by an external ping message to the server for obvious reasons.

Here's what I tried:

`./bin/spark-submit --deploy-mode cluster --class org.apache.spark.examples.SparkPi --master k8s://192.168.99.100:8443 --conf spark.executor.instances=5 --conf spark.app.name=iobidele --conf spark.kubernetes.namespace=iobidele --conf spark.kubernetes.driver.docker.image=iyanuobidele/spark-driver:snapshot --conf spark.kubernetes.executor.docker.image=iyanuobidele/spark-executor:snapshot /home/iyanu/Downloads/original-spark-examples_2.11-2.1.0-SNAPSHOT.jar`

On a different cl, I tried this:
`curl http://192.168.99.100:8443/v1/submissions/ping`

Here's what happened to the running SparkJob:

```./bin/spark-submit --deploy-mode cluster --class org.apache.spark.examples.SparkPi --master k8s://192.168.99.100:8443 --conf spark.executor.instances=5 --conf spark.app.name=iobidele --conf spark.kubernetes.namespace=iobidele --conf spark.kubernetes.driver.docker.image=iyanuobidele/spark-driver:snapshot --conf spark.kubernetes.executor.docker.image=iyanuobidele/spark-executor:snapshot /home/iyanu/Downloads/original-spark-examples_2.11-2.1.0-SNAPSHOT.jar
2017-02-01 15:53:18 INFO  Client:54 - Starting application iobidele-1485993198059 in Kubernetes...
2017-02-01 15:53:18 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2017-02-01 15:53:18 INFO  SecurityManager:54 - Changing view acls to: iyanu
2017-02-01 15:53:18 INFO  SecurityManager:54 - Changing modify acls to: iyanu
2017-02-01 15:53:18 INFO  SecurityManager:54 - Changing view acls groups to: 
2017-02-01 15:53:18 INFO  SecurityManager:54 - Changing modify acls groups to: 
2017-02-01 15:53:18 INFO  SecurityManager:54 - SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(iyanu); groups with view permissions: Set(); users  with modify permissions: Set(iyanu); groups with modify permissions: Set()
2017-02-01 15:53:19 INFO  LoggingPodStatusWatcher:54 - Application status for iobidele-1485993198059 (phase: unknown)
2017-02-01 15:53:20 INFO  LoggingPodStatusWatcher:54 - Application status for iobidele-1485993198059 (phase: Pending)
2017-02-01 15:53:20 INFO  LoggingPodStatusWatcher:54 - Phase changed, new state: 
	 pod name: iobidele-1485993198059
	 namespace: iobidele
	 labels: spark-app-id -> iobidele-1485993198059, spark-app-name -> iobidele, spark-driver -> iobidele-1485993198059
	 pod uid: 9bc831ff-e8d9-11e6-859a-0800278e258e
	 creation time: 2017-02-01T23:53:20Z
	 service account name: default
	 volumes: spark-submission-secret-volume, default-token-75z7v
	 node name: N/A
	 start time: N/A
	 container images: N/A
	 phase: Pending
         ...............................
```

once the ping request is sent, this happens:

```
2017-02-01 15:54:09 INFO  LoggingPodStatusWatcher:54 - Application status for iobidele-1485993198059 (phase: Running)
2017-02-01 15:54:10 INFO  LoggingPodStatusWatcher:54 - Application status for iobidele-1485993198059 (phase: Running)
2017-02-01 15:54:11 INFO  LoggingPodStatusWatcher:54 - Application status for iobidele-1485993198059 (phase: Running)
2017-02-01 15:54:12 INFO  LoggingPodStatusWatcher:54 - Application status for iobidele-1485993198059 (phase: Running)
2017-02-01 15:54:13 INFO  LoggingPodStatusWatcher:54 - Application status for iobidele-1485993198059 (phase: Running)
2017-02-01 15:54:14 INFO  LoggingPodStatusWatcher:54 - Application status for iobidele-1485993198059 (phase: Running)
2017-02-01 15:54:15 INFO  LoggingPodStatusWatcher:54 - Application status for iobidele-1485993198059 (phase: Running)
2017-02-01 15:54:16 INFO  LoggingPodStatusWatcher:54 - Application status for iobidele-1485993198059 (phase: Running)
2017-02-01 15:54:17 INFO  LoggingPodStatusWatcher:54 - Application status for iobidele-1485993198059 (phase: Running)
2017-02-01 15:54:18 INFO  LoggingPodStatusWatcher:54 - Application status for iobidele-1485993198059 (phase: Running)
2017-02-01 15:54:19 INFO  LoggingPodStatusWatcher:54 - Application status for iobidele-1485993198059 (phase: Running)
2017-02-01 15:54:19 INFO  LoggingPodStatusWatcher:54 - Application status for iobidele-1485993198059 (phase: Running)
2017-02-01 15:54:20 ERROR Client:91 - The driver pod with name iobidele-1485993198059 in namespace iobidele was not ready in 60 seconds.
Latest phase from the pod is: Running
The pod had no final message.

Driver container last state: Waiting
Driver container wait reason: CrashLoopBackOff
Driver container message: Back-off 40s restarting failed container=spark-kubernetes-driver pod=iobidele-1485993198059_iobidele(9bc831ff-e8d9-11e6-859a-0800278e258e)

java.util.concurrent.TimeoutException: Timeout waiting for task.
	at org.spark_project.guava.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:276)
	at org.spark_project.guava.util.concurrent.AbstractFuture.get(AbstractFuture.java:96)
	at org.apache.spark.deploy.kubernetes.Client$$anonfun$run$6$$anonfun$apply$5$$anonfun$apply$7.apply(Client.scala:185)
	at org.apache.spark.deploy.kubernetes.Client$$anonfun$run$6$$anonfun$apply$5$$anonfun$apply$7.apply(Client.scala:144)
	at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2530)
	at org.apache.spark.deploy.kubernetes.Client$$anonfun$run$6$$anonfun$apply$5.apply(Client.scala:144)
	at org.apache.spark.deploy.kubernetes.Client$$anonfun$run$6$$anonfun$apply$5.apply(Client.scala:129)
	at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2530)
	at org.apache.spark.deploy.kubernetes.Client$$anonfun$run$6.apply(Client.scala:129)
	at org.apache.spark.deploy.kubernetes.Client$$anonfun$run$6.apply(Client.scala:103)
	at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2530)
	at org.apache.spark.deploy.kubernetes.Client.run(Client.scala:103)
	at org.apache.spark.deploy.kubernetes.Client$.main(Client.scala:650)
	at org.apache.spark.deploy.kubernetes.Client.main(Client.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:748)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:178)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:117)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
2017-02-01 15:54:20 INFO  LoggingPodStatusWatcher:54 - Application status for iobidele-1485993198059 (phase: Running)
Exception in thread "OkHttp https://192.168.99.100:8443/api/v1/namespaces/iobidele/pods?labelSelector=spark-app-id%3Diobidele-1485993198059,spark-app-name%3Diobidele,spark-driver%3Diobidele-1485993198059&resourceVersion=1092632&watch=true WebSocket" java.lang.NullPointerException
	at org.spark_project.guava.base.Preconditions.checkNotNull(Preconditions.java:191)
	at org.spark_project.guava.util.concurrent.AbstractFuture.setException(AbstractFuture.java:201)
	at org.spark_project.guava.util.concurrent.SettableFuture.setException(SettableFuture.java:68)
	at org.apache.spark.deploy.kubernetes.Client$DriverPodWatcher.onClose(Client.scala:448)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onClose(WatchConnectionManager.java:259)
	at okhttp3.internal.ws.RealWebSocket.peerClose(RealWebSocket.java:197)
	at okhttp3.internal.ws.RealWebSocket.access$200(RealWebSocket.java:38)
	at okhttp3.internal.ws.RealWebSocket$1$2.execute(RealWebSocket.java:84)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-02-01 15:54:20 INFO  LoggingPodStatusWatcher:54 - Application iobidele-1485993198059 ended with final phase Running
Exception in thread "main" org.apache.spark.SparkException: The driver pod with name iobidele-1485993198059 in namespace iobidele was not ready in 60 seconds.
Latest phase from the pod is: Running
The pod had no final message.

Driver container last state: Waiting
Driver container wait reason: CrashLoopBackOff
Driver container message: Back-off 40s restarting failed container=spark-kubernetes-driver pod=iobidele-1485993198059_iobidele(9bc831ff-e8d9-11e6-859a-0800278e258e)

	at org.apache.spark.deploy.kubernetes.Client$$anonfun$run$6$$anonfun$apply$5$$anonfun$apply$7.apply(Client.scala:191)
	at org.apache.spark.deploy.kubernetes.Client$$anonfun$run$6$$anonfun$apply$5$$anonfun$apply$7.apply(Client.scala:144)
	at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2530)
	at org.apache.spark.deploy.kubernetes.Client$$anonfun$run$6$$anonfun$apply$5.apply(Client.scala:144)
	at org.apache.spark.deploy.kubernetes.Client$$anonfun$run$6$$anonfun$apply$5.apply(Client.scala:129)
	at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2530)
	at org.apache.spark.deploy.kubernetes.Client$$anonfun$run$6.apply(Client.scala:129)
	at org.apache.spark.deploy.kubernetes.Client$$anonfun$run$6.apply(Client.scala:103)
	at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:2530)
	at org.apache.spark.deploy.kubernetes.Client.run(Client.scala:103)
	at org.apache.spark.deploy.kubernetes.Client$.main(Client.scala:650)
	at org.apache.spark.deploy.kubernetes.Client.main(Client.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:748)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:178)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:117)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.util.concurrent.TimeoutException: Timeout waiting for task.
	at org.spark_project.guava.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:276)
	at org.spark_project.guava.util.concurrent.AbstractFuture.get(AbstractFuture.java:96)
	at org.apache.spark.deploy.kubernetes.Client$$anonfun$run$6$$anonfun$apply$5$$anonfun$apply$7.apply(Client.scala:185)
	... 20 more
```

I probably did the ping two times, and you can see the direct effect in the logs.

**Comment by mccheah** [comment]
Hm, @iyanuobidele I think there's something else at play here - more detailed logging can be obtained from the failed ping once we have [this change](https://github.com/apache-spark-on-k8s/spark/pull/69/files#diff-656c1210d27ee4ae4572324461c16f0aR34) but pinging the server once shouldn't cause all subsequent pings to fail.

**Comment by mccheah** [comment]
@foxish we can look into the readiness probe then. I would like to have the endpoint be to a health check path on the server, but right now the server strictly picks SSL or plaintext mode - it won't listen on both at the same time. That being said we should probably serve the ping over plaintext anyways.

**Comment by iyanuobidele** [comment]
@mccheah that's correct. 

But should this behavior be accepted ? From what I see in the logs, the ping triggered a readiness check again while the job is running. This leads to a timeout exception that rethrows a sparkException and then the deletion of the driver pod while it was already running.

**Comment by iyanuobidele** [comment]
I think once we find another way of finding out if the restServer is ready, we could look for a way to convert the current websocket implementation to a SSE. I was talking about this on this other [issue](https://github.com/apache-spark-on-k8s/spark/issues/63)

**Comment by mccheah** [comment]
@foxish ReadinessProbe's HttpGet API supports using HTTPS - but how does the kubelet set up the SSL connection? What certificates does it use?

**Comment by foxish** [comment]
@mccheah, it should just [ignore certificate validation](https://github.com/kubernetes/kubernetes/blob/6a4d5cd7cc58e28c20ca133dab7b0e9e56192fe3/pkg/probe/http/http.go#L34). All it needs is that you change the scheme of the probe.
