### ISSUE TITLE
Exception when running integration tests with minikube upgrade available

### ISSUE THREAD

**Issue by ash211** [apache-spark-on-k8s/spark#96]
Saw this while running integration tests:

`build/mvn -B integration-test -Pkubernetes -Pkubernetes-integration-tests -pl resource-managers/kubernetes/integration-tests -am -Dtest=none -DwildcardSuites=org.apache.spark.deploy.kubernetes.integrationtest.KubernetesSuite`:

```
Exception encountered when invoking run on a nested suite - Unknown status There is a newer version of minikube available (v0.16.0).  Download it here: *** ABORTED ***
  java.lang.IllegalStateException: Unknown status There is a newer version of minikube available (v0.16.0).  Download it here:
  at org.apache.spark.deploy.kubernetes.integrationtest.minikube.Minikube$$anonfun$getMinikubeStatus$2.apply(Minikube.scala:69)
  at org.apache.spark.deploy.kubernetes.integrationtest.minikube.Minikube$$anonfun$getMinikubeStatus$2.apply(Minikube.scala:69)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.deploy.kubernetes.integrationtest.minikube.Minikube$.getMinikubeStatus(Minikube.scala:69)
  at org.apache.spark.deploy.kubernetes.integrationtest.minikube.Minikube$.startMinikube(Minikube.scala:51)
  at org.apache.spark.deploy.kubernetes.integrationtest.KubernetesSuite.beforeAll(KubernetesSuite.scala:82)
  at org.scalatest.BeforeAndAfterAll$class.beforeAll(BeforeAndAfterAll.scala:187)
  at org.apache.spark.SparkFunSuite.beforeAll(SparkFunSuite.scala:31)
  at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:253)
  at org.apache.spark.deploy.kubernetes.integrationtest.KubernetesSuite.org$scalatest$BeforeAndAfter$$super$run(KubernetesSuite.scala:46)
```

Should either set `minikube config set WantUpdateNotification false` (https://github.com/kubernetes/minikube/blob/master/pkg/minikube/notify/notify.go#L68) or parse the results more rigorously

**Comment by foxish** [comment]
I'm starting to wonder if this kind of automation is a good idea, although it is convenient at times. We're relying quite a bit on minikube's messages and not any real API. Perhaps we should let our integration tests run on *any* kubernetes cluster that is specified, rather than relying on Minikube. In the future, as minikube changes in other ways, we may run into more issues. Thoughts on separating out integration tests from minikube?

**Comment by ash211** [comment]
I'd support being able to run against any kubernetes cluster rather than just the embedded minikube ones.  We shouldn't rely on anything minikube-specific, so if there are any assumptions there moving to alternate k8s clusters would ferret them out.

I'll file another issue for supporting running tests against any specified k8s apiserver.  Maybe should read apiserver config from `kubectl config` too.

EDIT: https://github.com/apache-spark-on-k8s/spark/issues/100
